# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


permalink: /:categories/:year/:month/:day/:title/index.html

# Site settings
title: subtxt/in
email: drew@subtxt.in
description: > # this means to ignore newlines until "baseurl:"
  Personal website for drew gordon. Writings about technology in libraries and archives, culture, literature, language, and data
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://subtxt.in" # the base hostname & protocol for your site
twitter_username: dogrdon
github_username:  dogrdon

# Build settings
markdown: kramdown

analytics :
    provider : google
    google :
        tracking_id : 'UA-49049624-1'


archive_path: /archive/
categories_path : /categories/
tags_path : /tags/
#atom_path : /atom.xml
rss_path : /rss.xml
